<a href="https://colab.research.google.com/github/maitysuvo19/Semantic_textual_similarity/blob/main/Word2vec_sts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#basic imports
import pandas as pd
import numpy as np

In [ ]:
#loading the data set
df=pd.read_csv('/content/drive/MyDrive/nlp data/Text_Similarity_Dataset.csv')

In [ ]:
#view first few rows of the dataset
df.head(3)

Unique_ID  ...                                              text2
0          0  ...  newcastle 2-1 bolton kieron dyer smashed home ...
1          1  ...  nasdaq planning $100m share sale the owner of ...
2          2  ...  ruddock backs yapp s credentials wales coach m...

[3 rows x 3 columns]

In [ ]:
#importing packages for pre-processing texts
import re    # for regular expressions 
import nltk  # for text manipulation 
nltk.download('stopwords')
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
import string 

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stop_words = stopwords.words('english')
stemmer = SnowballStemmer('english')
text_cleaning_re = "@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+"

In [ ]:
#function to preprocess texts
def preprocess(text, stem=True):
  text = re.sub(text_cleaning_re, ' ', str(text).lower()).strip()
  tokens = []
  for token in text.split():
    if token not in stop_words:
      if stem:
        tokens.append(stemmer.stem(token))
      else:
        tokens.append(token)
  return " ".join(tokens)

In [ ]:
df.text1 = df.text1.apply(lambda x: preprocess(x))
df.text2 = df.text2.apply(lambda x: preprocess(x))

In [ ]:
#preprocessed dataframe
df.head()

Unique_ID  ...                                              text2
0          0  ...  newcastl 2 1 bolton kieron dyer smash home win...
1          1  ...  nasdaq plan 100m share sale owner technolog do...
2          2  ...  ruddock back yapp credenti wale coach mike rud...
3          3  ...  mci share climb takeov bid share us phone comp...
4          4  ...  media gadget get move pocket size devic let pe...

[5 rows x 3 columns]

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
#Load W2V model. This will take some time. 
%time w2v_model = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/nlp data/GoogleNews-vectors-negative300.bin.gz", binary=True)
print('done loading Word2Vec')

CPU times: user 2min 9s, sys: 6.74 s, total: 2min 16s
Wall time: 2min 16s
done loading Word2Vec


In [ ]:
#What is the vector representation for a word? 
w2v_model['computer']

array([ 1.07421875e-01, -2.01171875e-01,  1.23046875e-01,  2.11914062e-01,
       -9.13085938e-02,  2.16796875e-01, -1.31835938e-01,  8.30078125e-02,
        2.02148438e-01,  4.78515625e-02,  3.66210938e-02, -2.45361328e-02,
        2.39257812e-02, -1.60156250e-01, -2.61230469e-02,  9.71679688e-02,
       -6.34765625e-02,  1.84570312e-01,  1.70898438e-01, -1.63085938e-01,
       -1.09375000e-01,  1.49414062e-01, -4.65393066e-04,  9.61914062e-02,
        1.68945312e-01,  2.60925293e-03,  8.93554688e-02,  6.49414062e-02,
        3.56445312e-02, -6.93359375e-02, -1.46484375e-01, -1.21093750e-01,
       -2.27539062e-01,  2.45361328e-02, -1.24511719e-01, -3.18359375e-01,
       -2.20703125e-01,  1.30859375e-01,  3.66210938e-02, -3.63769531e-02,
       -1.13281250e-01,  1.95312500e-01,  9.76562500e-02,  1.26953125e-01,
        6.59179688e-02,  6.93359375e-02,  1.02539062e-02,  1.75781250e-01,
       -1.68945312e-01,  1.21307373e-03, -2.98828125e-01, -1.15234375e-01,
        5.66406250e-02, -

In [ ]:
text1=df.text1.tolist()
text2=df.text2.tolist()

In [ ]:
#downloading one model from spacy
!python -m spacy download en

✔ Download and installation successful
You can now load the model via spacy.load('en_core_web_sm')
✔ Linking successful
/usr/local/lib/python3.7/dist-packages/en_core_web_sm -->
/usr/local/lib/python3.7/dist-packages/spacy/data/en
You can now load the model via spacy.load('en')


In [ ]:
#getting full vector form of afull sentence
import spacy
nlp = spacy.load('en')
# process a sentence using the model
mydoc1 = nlp("He claimed the first prize")
#Get a vector for individual words
#print(doc[0].vector) #vector for 'Canada', the first word in the text 
print(mydoc1.vector) #Averaged vector for the entire sentence

[ 0.3620209  -0.01589755  0.73795205  0.6619536   0.6915089   0.06288836
  0.0065306   0.4606282   1.8843695   0.7376335  -0.08946385  0.35756987
 -1.0187318   0.4320526  -2.1145573  -0.83622444 -0.3605052   0.48296326
 -2.1519215  -0.71831405 -0.21233864 -1.3039311  -0.9245714  -0.4893407
 -1.9556987   0.20174666 -1.2100987  -1.4504039   1.0124367  -0.6858812
  0.93202245 -0.306467   -0.5500347  -0.34786582  1.2820048  -1.88637
 -0.5202693  -0.98329973 -1.3782289  -0.49845853  2.0106692  -0.00754814
  0.43313426 -0.3719442   0.6082352   1.0625111   0.7867502   0.06375372
 -0.1465433   0.756879    0.5898582  -1.7789272   0.5927583   0.03830198
 -0.40252534  1.1348393   1.2063932   1.2171171   0.15282646 -0.49123463
 -0.47331238 -1.0698674   0.66504586  1.0575447   0.20579156  1.216759
  0.60096806 -0.6685052  -1.6405945   1.0489334  -0.1793476   1.181071
 -1.6496738  -0.26168957 -0.12555365 -0.36089373  0.7592236  -0.8700713
 -1.8870013  -0.61012715  1.3409507  -1.2413847   0.72017825 

In [ ]:
(mydoc1.vector)

array([ 0.3620209 , -0.01589755,  0.73795205,  0.6619536 ,  0.6915089 ,
        0.06288836,  0.0065306 ,  0.4606282 ,  1.8843695 ,  0.7376335 ,
       -0.08946385,  0.35756987, -1.0187318 ,  0.4320526 , -2.1145573 ,
       -0.83622444, -0.3605052 ,  0.48296326, -2.1519215 , -0.71831405,
       -0.21233864, -1.3039311 , -0.9245714 , -0.4893407 , -1.9556987 ,
        0.20174666, -1.2100987 , -1.4504039 ,  1.0124367 , -0.6858812 ,
        0.93202245, -0.306467  , -0.5500347 , -0.34786582,  1.2820048 ,
       -1.88637   , -0.5202693 , -0.98329973, -1.3782289 , -0.49845853,
        2.0106692 , -0.00754814,  0.43313426, -0.3719442 ,  0.6082352 ,
        1.0625111 ,  0.7867502 ,  0.06375372, -0.1465433 ,  0.756879  ,
        0.5898582 , -1.7789272 ,  0.5927583 ,  0.03830198, -0.40252534,
        1.1348393 ,  1.2063932 ,  1.2171171 ,  0.15282646, -0.49123463,
       -0.47331238, -1.0698674 ,  0.66504586,  1.0575447 ,  0.20579156,
        1.216759  ,  0.60096806, -0.6685052 , -1.6405945 ,  1.04

In [ ]:
text1[0]

'savvi searcher fail spot ad internet search engin user odd mix naiv sophist suggest report search habit report us pew research center reveal 87 searcher usual find look use search engin also show spot differ paid result organ one report reveal 84 net user say regular use googl ask jeev msn yahoo onlin almost 50 question said would trust search engin much less knew inform paid result hidden accord figur gather pew research averag user spend 43 minut per month carri 34 separ search look 1 9 webpag hunt signific chunk net user 36 carri search least week 29 ask look everi week 44 question inform look critic inform simpli find search engin user also tend loyal found site feel trust tend stick accord pew research 44 searcher use singl search engin 48 use two three small number 7 consult three site toni macklin spokesman ask jeev said result reflect research show peopl use differ search engin way site gather inform mean provid differ result queri despit like search site half question said co

In [ ]:
text2[0]

'newcastl 2 1 bolton kieron dyer smash home winner end bolton 10 game unbeaten run lee bowyer put newcastl ahead fed stephen carr right flank sprint area power home header result cross wander hit back stelio giannakopoulo end fluid pass move well struck volley dyer last word game chanc pounc loos ball alan shearer shot block fire top corner neither side lack urgenc earli stage game plenti tackl fli opportun front goal harder come bolton keeper jussi jaaskelainen make two save quick success midway first half keep shearer low shot dyer close rang header goalmouth action note almost noth magpi took lead 35 minut bowyer found space neat turn half way line stride forward pick carr right continu run perfect time made way box met carr cross downward header far corner bolton produc littl go forward point respond well level within six minut thank smart finish giannakopoulo jay jay okocha twist turn edg area neat exchang pass involv kevin davi gari speed greek striker found bottom corner first t

In [ ]:
example_vec1=(nlp(text1[0])).vector

In [ ]:
example_vec1

array([-0.5353382 , -0.42059356, -0.97794455,  1.3393344 ,  0.7241896 ,
        1.1390245 , -0.3333871 ,  0.7842466 ,  0.8616824 ,  1.8246562 ,
        0.6621302 ,  0.12300424,  0.56635356, -1.6600674 , -1.194273  ,
       -0.29328278,  0.0148082 ,  1.1751214 , -0.7738678 , -0.4284438 ,
        1.0898249 ,  0.02041132, -0.8989274 , -0.13136366, -1.3464755 ,
       -0.24311695, -0.39513317, -1.8421342 ,  1.8940842 , -1.155638  ,
        0.82116693, -0.36959195,  1.280659  , -1.6239961 , -0.14693405,
       -0.9443388 ,  1.7624456 , -1.171524  , -0.25707465,  0.5854374 ,
        1.6202538 ,  1.1044476 , -0.27875733, -2.4352345 , -0.33411497,
        0.06258636, -0.19126832, -0.2857032 , -0.3224051 ,  0.5731664 ,
       -0.08110671, -1.4598508 ,  0.21442264, -0.30378053, -1.9464116 ,
        0.7900619 ,  0.75666636,  0.82911044,  0.37478626,  0.33358237,
        1.7288601 , -1.4223211 ,  0.54945254, -0.03862204,  1.2170622 ,
       -0.47391173,  0.81001514, -1.0284138 , -0.7223689 ,  0.96

In [ ]:
example_vec2=(nlp(text2[0])).vector

In [ ]:
example_vec2

array([ 0.09586918, -0.7180681 , -1.3572825 ,  1.1032252 ,  0.642228  ,
        1.7835149 , -0.41683567,  0.8083387 ,  0.8579135 ,  1.6354378 ,
        1.5563961 , -0.11976955,  1.1860647 , -1.2702216 , -1.0500904 ,
       -0.28734615,  0.31025988,  0.8582171 , -1.1746397 , -0.6948666 ,
        1.1033419 , -0.78444064, -0.58646387, -0.58037865, -0.96302783,
       -0.25909606, -0.5367973 , -1.2904718 ,  1.9021246 , -1.3634243 ,
        0.4709608 , -0.7502414 ,  0.6751075 , -1.3818852 , -0.34907225,
       -1.4924061 ,  2.277174  , -1.0592152 , -0.643306  ,  0.29338437,
        1.5544162 ,  1.2917528 ,  0.02740993, -1.7540668 , -0.18536858,
       -0.00404733, -0.3960101 , -0.51909834, -0.6289124 ,  0.6968914 ,
       -0.7837415 , -0.9764297 ,  0.20004973, -0.63890374, -1.9306512 ,
        0.6715479 ,  0.94309807,  1.6235938 , -0.15712474, -0.23432456,
        0.9549279 , -1.1742626 ,  0.6272981 , -0.26517275,  1.5626752 ,
       -0.1158542 ,  0.6806603 , -1.4488014 ,  0.19554615,  0.93

In [ ]:
import scipy

In [ ]:
print(1-scipy.spatial.distance.cosine(example_vec1,example_vec2))

0.9173871278762817


In [ ]:
similarity_score=[]
for index, row in df.iterrows():
  vec1=(nlp(text1[index])).vector
  vec2=(nlp(text2[index])).vector
  cosine = scipy.spatial.distance.cosine(vec1,vec2)
  similarity_score.append(1-cosine)

In [ ]:
#transforming similarity score sclae [-1,1] to [0,1]
Similarity_Score = [((x+1)/2) for x in similarity_score]

In [ ]:
df=df.assign(Similarity_Score=Similarity_Score)

In [ ]:
df.head()

Unique_ID  ... Similarity_Score
0          0  ...         0.958694
1          1  ...         0.977436
2          2  ...         0.930323
3          3  ...         0.981575
4          4  ...         0.992663

[5 rows x 4 columns]

In [ ]:
df=df[['Unique_ID','Similarity_Score']]
df.head()

Unique_ID  Similarity_Score
0          0          0.958694
1          1          0.977436
2          2          0.930323
3          3          0.981575
4          4          0.992663

In [ ]:
from google.colab import files
df.to_csv('df_word2vec_sts.csv')
files.download('df_word2vec_sts.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
#for printing
!wget -nc https://raw.githubusercontent.com/brpy/colab-pdf/master/colab_pdf.py
from colab_pdf import colab_pdf
colab_pdf('Word2vec-sts_1.ipynb')

File ‘colab_pdf.py’ already there; not retrieving.





[NbConvertApp] Converting notebook /content/drive/My Drive/Colab Notebooks/Word2vec-sts_1.ipynb to pdf
[NbConvertApp] Writing 57168 bytes to ./notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: [u'xelatex', u'./notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'./notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 44514 bytes to /content/drive/My Drive/Word2vec-sts_1.pdf


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'File ready to be Downloaded and Saved to Drive'